services:
    postgres:
        image: postgres:latest
        container_name: postgres_zakat
        environment:
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
        env_file:
            - ./.env
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
            - ./postgresql.conf:/etc/postgresql/postgresql.conf
        ports:
            - '5432:5432'
volumes:
    postgres:
